package com.project.invoiceHelper;

public enum SearchOperation {
	GREATER_THAN,
	LESS_THAN,
	GREATER_THAN_EQUAL,
	GREATER_THAN_EQUAL_LOCALDATE,
	LESS_THAN_EQUAL,
	LESS_THAN_EQUAL_LOCALDATE,
	NOT_EQUAL,
	EQUAL,
	BETWEEN
}
